import { getAllMarkdownContent, MarkdownContent } from '../../lib/markdown'

export interface Misc {
  id: string
  title: string
  description: string
  category?: string[]
  date?: string
  link?: string
}

// Convert MarkdownContent to Misc interface
function markdownToMisc(content: MarkdownContent): Misc {
  return {
    id: content.id,
    title: content.title,
    description: content.description,
    category: content.category,
    date: content.date,
    link: content.link,
  }
}

// Get all miscs from markdown files
export async function getMiscs(): Promise<Misc[]> {
  const markdownContent = await getAllMarkdownContent('misc')
  return markdownContent.map(markdownToMisc)
}

// Fallback static data for when markdown files don't exist
export const miscs: Misc[] = [
  {
    id: "permute-mississippi",
    title: "how many ways to permute the word mississippi?",
    description: "a review of permutations and combinations",
    category: ["Learning"],
    date: "2025"
  },
  {
    id: "history-of-ai",
    title: "the history of artificial intelligence",
    description: "let's go back in time to where it all began",
    category: ["Technical"],
    date: "2025"
  },
  {
    id: "handshakes-to-sam-altman",
    title: "how many handshakes are you away from sam altman?",
    description: "a fun network experiment to see how connected we really are",
    category: ["Technical"],
    date: "2025"
  },
  {
    id: "what-is-npm",
    title: "so...what exactly is an npm?",
    description: "unpacking the mystery behind npm and its role in modern web development",
    category: ["Technical"],
  },
  {
    id: "daily-learn-log",
    title: "daily learn log",
    description: "a log of what i've learned each day",
    category: ["Learning"],
  },
  {
    id: "failed-llm-output",
    title: "a log of failed outputs generated by llms",
    description: "i just think it's interesting to keep a log of examples when llms failed to generate what i expected",
    category: ["Learning"],
  }
]

